### ISSUE TITLE
Supervisor throws error when enabling watchdog feature for this add-on.

### ISSUE THREAD

**Issue by vandalon** [hassio-addons/addon-ssh#269]
# Problem/Motivation
When enabling the watchdog flag for this add-on the supervisor start throwing the following error every 2 minutes:

```
May 23 20:45:06 homeassistant a9d4909f5b1b[421]: 2021-05-23 22:45:06 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [281472517307216] Error handling message: Unknown error
May 23 20:45:06 homeassistant a9d4909f5b1b[421]: Traceback (most recent call last):
May 23 20:45:06 homeassistant a9d4909f5b1b[421]:   File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 98, in async_handle
May 23 20:45:06 homeassistant a9d4909f5b1b[421]:     handler(self.hass, self, schema(msg))
May 23 20:45:06 homeassistant a9d4909f5b1b[421]:   File "/config/custom_components/browser_mod/connection.py", line 44, in handle_update
May 23 20:45:06 homeassistant a9d4909f5b1b[421]:     devices[deviceID].update(msg.get("data", None))
May 23 20:45:06 homeassistant a9d4909f5b1b[421]:   File "/config/custom_components/browser_mod/connection.py", line 101, in update
May 23 20:45:06 homeassistant a9d4909f5b1b[421]:     self.media_player.data = data.get("player")
May 23 20:45:06 homeassistant a9d4909f5b1b[421]:   File "/config/custom_components/browser_mod/helpers.py", line 104, in data
May 23 20:45:06 homeassistant a9d4909f5b1b[421]:     self.updated()
May 23 20:45:06 homeassistant a9d4909f5b1b[421]:   File "/config/custom_components/browser_mod/media_player.py", line 42, in updated
May 23 20:45:06 homeassistant a9d4909f5b1b[421]:     self.schedule_update_ha_state()
May 23 20:45:06 homeassistant a9d4909f5b1b[421]:   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in schedule_update_ha_state
May 23 20:45:06 homeassistant a9d4909f5b1b[421]:     self.hass.add_job(self.async_update_ha_state(force_refresh))  # type: ignore
May 23 20:45:06 homeassistant a9d4909f5b1b[421]: AttributeError: 'NoneType' object has no attribute 'add_job'
```

## Expected behavior
Not to throw the above error :P

## Actual behavior
Throwing the error above :D

## Steps to reproduce
Enable the watchdog option in for this add-on when it's running. 

## Proposed changes

Sorry, did not have to time to figure this out.

**Comment by frenck** [comment]
This add-on does not provide a watchdog feature.

This is not an add-on issue.

**Comment by vandalon** [comment]
Does this watchdog option then shows for every add-on, even if it has no support?

<img width="794" alt="image" src="https://user-images.githubusercontent.com/3370317/119276172-aac25980-bc19-11eb-939b-bdca8425e7db.png">

**Comment by frenck** [comment]
yes

**Comment by vandalon** [comment]
Ok, clear, sorry for this then.
