### ISSUE TITLE
Error updating SSH & Web Terminal: 'AddonManager.update' blocked from execution, no host internet connection

### ISSUE THREAD

**Issue by vlad36N** [hassio-addons/addon-ssh#549]
# Problem/Motivation

Error updating SSH & Web Terminal: 'AddonManager.update' blocked from execution, no host internet connection

Home Assistant 2023.4.6 
Supervisor 2023.04.1 
Operating System 10.1 
Frontend 20230411.1 - latest 

Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/update.py:169
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 07:07:04 (1 occurrences)
Last logged: 07:07:04

[547233210256] Error updating SSH & Web Terminal: 'AddonManager.update' blocked from execution, no host internet connection
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 167, in async_install
    await async_update_addon(self.hass, slug=self._addon_slug, backup=backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 51, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: 'AddonManager.update' blocked from execution, no host internet connection

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1820, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1857, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 216, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 798, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 977, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 838, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 156, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 417, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 169, in async_install
    raise HomeAssistantError(f"Error updating {self.title}: {err}") from err
homeassistant.exceptions.HomeAssistantError: Error updating SSH & Web Terminal: 'AddonManager.update' blocked from execution, no host internet connection

**Comment by frenck** [comment]
> Error updating SSH & Web Terminal: 'AddonManager.update' blocked from execution, no host internet connection

This is not an add-on issue and out of control of the add-on.
The Home Assistant Supervisor blocks updates, as it has no available internet connection.

Nothing I can do from an add-on perspective. If you think this is an bug, please report it with the Home Assistant project.

../Frenck
