### ISSUE TITLE
Visual Studio Code Remote - SSH extension not working with this addon

### ISSUE THREAD

**Issue by danVnest** [hassio-addons/addon-ssh#648]
# Problem

The [Visual Studio Code Remote - SSH extension](https://code.visualstudio.com/docs/remote/ssh) does not work with this addon with my setup. 
I previously used [this SSH addon](https://github.com/mietzen/hassio-addons/tree/main/vscode-remote-ssh) with no issue, however, it does not expose the `addon_configs` directory and overall I much prefer this addon.

## Expected behavior

I want to use Visual Studio Code remotely to maintain and develop [my home assistant setup](https://github.com/danVnest/home-assistant/).

## Actual behavior

The Visual Studio Code extension crashes with the following log:
<details>
  <summary>log</summary>

```
[23:25:51.945] Log Level: 2
[23:25:51.952] SSH Resolver called for "ssh-remote+home-assistant.local", attempt 1
[23:25:51.953] "remote.SSH.useLocalServer": true
[23:25:51.953] "remote.SSH.useExecServer": false
[23:25:51.953] "remote.SSH.path": undefined
[23:25:51.953] "remote.SSH.configFile": undefined
[23:25:51.953] "remote.SSH.useFlock": true
[23:25:51.953] "remote.SSH.lockfilesInTmp": false
[23:25:51.953] "remote.SSH.localServerDownload": auto
[23:25:51.953] "remote.SSH.remoteServerListenOnSocket": false
[23:25:51.954] "remote.SSH.showLoginTerminal": false
[23:25:51.954] "remote.SSH.defaultExtensions": []
[23:25:51.954] "remote.SSH.loglevel": 2
[23:25:51.954] "remote.SSH.enableDynamicForwarding": true
[23:25:51.954] "remote.SSH.enableRemoteCommand": false
[23:25:51.954] "remote.SSH.serverPickPortsFromRange": {}
[23:25:51.954] "remote.SSH.serverInstallPath": {}
[23:25:51.958] VS Code version: 1.84.2
[23:25:51.958] Remote-SSH version: remote-ssh@0.107.0
[23:25:51.958] darwin x64
[23:25:51.961] SSH Resolver called for host: home-assistant.local
[23:25:51.961] Setting up SSH remote "home-assistant.local"
[23:25:51.963] Acquiring local install lock: /var/folders/bm/cjyxyrdd2rz200000gn/T/vscode-remote-ssh-7f6ca7ae-install.lock
[23:25:51.964] Looking for existing server data file at /Users/user/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-7f6ca7ae-1a5daa3a02319d7768e-0.107.0-tr/data.json
[23:25:51.964] Using commit id "1a5daa3a02319d7768e" and quality "stable" for server
[23:25:51.967] Install and start server if needed
[23:25:51.968] PATH: /Users/user/.pyenv/shims:/usr/local/bin:/usr/local/sbin:/Users/user/.bin:/usr/local/bin:/usr/local/sbin:/Users/user/.pyenv/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/X11/bin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/Applications/VMware Fusion.app/Contents/Public:/Users/user/Code/webOS_TV_SDK/CLI/bin
[23:25:51.968] Checking ssh with "ssh -V"
[23:25:51.976] > OpenSSH_9.4p1, LibreSSL 3.3.6
[23:25:51.979] askpass server listening on /var/folders/bm/cjyxyrdd2rz200000gn/T/vscode-ssh-askpass-25fa8752ed673f2db302ab06252736edc27dfebe.sock
[23:25:51.979] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/bm/cjyxyrdd2rz200000gn/T/vscode-ssh-askpass-2929164778da1e68d5c519f15377381e651d7546.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","63420","-o","ConnectTimeout=15","home-assistant.local"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/user/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-7f6ca7ae-1a5daa3a02319d7768e-0.107.0-tr/data.json"}
[23:25:51.979] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.VDWuQY7CKv/Listeners","SHELL":"/bin/zsh","DISPLAY":"/private/tmp/com.apple.launchd.0vis99Vpb0/org.xquartz:0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/bm/cjyxyrdd2rz200000gn/T/vscode-ssh-askpass-25fa8752ed673f2db302ab06252736edc27dfebe.sock"}
[23:25:51.980] Spawned 72592
[23:25:52.123] > local-server-1> Running ssh connection command: "-v -T -D 63420 -o ConnectTimeout=15 home-assistant.local"
[23:25:52.126] > local-server-1> Spawned ssh, pid=72602
[23:25:52.132] stderr> OpenSSH_9.4p1, LibreSSL 3.3.6
[23:25:52.463] stderr> debug1: Server host key: ssh-ed25519 SHA256:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[23:25:52.913] stderr> Authenticated to home-assistant.local ([e80::XXXX:XXXX:e88a:11f6%en0]:22) using "publickey".
[23:25:52.976] > 
> | |  | |                          /\           (_)   | |            | |  
> | |__| | ___  _ __ ___   ___     /  \   ___ ___ _ ___| |_ __ _ _ __ | |_ 
> |  __  |/ _ \| '_ \ _ \ / _ \   / /\ \ / __/ __| / __| __/ _\ | '_ \| __|
> | |  | | (_) | | | | | |  __/  / ____ \\__ \__ \ \__ \ || (_| | | | | |_ 
> |_|  |_|\___/|_| |_| |_|\___| /_/    \_\___/___/_|___/\__\__,_|_| |_|\__|
> 
> Welcome to the Home Assistant command line.
[23:25:52.984] > System information
[23:25:52.991] >   IPv4 addresses for wlan0: 
>   IPv4 addresses for end0:  192.168.0.79/24, 192.168.1.11/24
>   IPv6 addresses for end0:  fe80::XXXX:XXXX:e88a:11f6/64
[23:25:53.003] >   OS Version:               Home Assistant OS 11.1
>   Home Assistant Core:      2023.11.2
> 
>   Home Assistant URL:       http://home-assistant.local:8123
>   Observer URL:             http://home-assistant.local:4357
[23:25:53.005] > ready: 0d7e1079a474
[23:25:53.011] > Linux 6.1.21-v7l #1 SMP Thu Oct 26 14:35:16 UTC 2023
[23:25:53.011] Platform: linux
[23:25:53.015] > /bin/zsh
[23:25:53.015] Shell: zsh
[23:25:53.015] Creating bash subshell inside "zsh"
[23:25:53.024] > bash version:  5.2.15(1)-release
[23:25:53.082] > 0d7e1079a474: running
[23:25:53.114] stderr> Illegal option -p
[23:25:53.119] stderr> musl libc (armhf)
[23:25:53.119] stderr> Version 1.2.4
[23:25:53.119] stderr> Dynamic Program Loader
[23:25:53.119] stderr> Usage: /lib/ld-musl-armhf.so.1
[23:25:53.120] stderr>  [options] [--] pathname
[23:25:53.121] > Missing GLIBC >= 2.17!
> Found version 
> 0d7e1079a474$$1$$
[23:25:53.128] > Acquiring lock on /root/.vscode-server/bin/1a5daa3a02319d7768e/vscode-remote-lock.root.1a5daa3a02319d7768e
[23:25:53.141] > Installing to /root/.vscode-server/bin/1a5daa3a02319d7768e...
[23:25:53.152] > 0d7e1079a474%%1%%
[23:25:53.172] > Downloading with wget
[23:25:59.266] > Download complete
[23:25:59.294] > 0d7e1079a474%%2%%
> tar --version:
> tar (busybox) 1.36.1
[23:26:09.549] > Checking /root/.vscode-server/.1a5daa3a02319d7768e.log and /root/.vscode-server/.1a5daa3a02319d7768e.pid for a running server
[23:26:09.562] > Running ssh connection command... /root/.vscode-server/bin/1a5daa3a02319d7768e/bin/code-server --start-server --host=127.0.0.1 --accept-server-license-terms --enable-remote-auto-shutdown --port=0 --telemetry-level all   &> "/root/.vscode-server/.1a5daa3a02319d7768e.log" < /dev/null
> printenv:
[23:26:09.564] >     SHELL=/bin/zsh
>     CHARSET=UTF-8
>     PWD=/root
>     LOGNAME=root
>     TZ=Earth, probably
>     HOME=/root
>     LANG=C.UTF-8
>     VSCODE_AGENT_FOLDER=/root/.vscode-server
>     SSH_CONNECTION=fe80::XXX:XXXX:f659:42da%end0 63421 fe80::XXXX:XXXX:e88a:11f6%end0 22
>     USER=root
>     SUPERVISOR_TOKEN=377ffc86c023XXXXXXa9c4f7ce58e47af6e0
>     SHLVL=2
>     PAGER=less
>     SSH_CLIENT=fe80::XXXX:XXXX:f659:42da%end0 63421 22
>     LC_COLLATE=C
>     PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
>     MAIL=/var/mail/root
>     OLDPWD=/root/.vscode-server/bin/1a5daa3a02319d7768e
>     _=/bin/printenv
[23:26:09.574] stderr> rm: can't remove '/root/.vscode-server/.1a5daa3a02319d7768e.token': No such file or directory
[23:26:09.582] > Spawned remote server: 620
[23:26:09.593] > Waiting for server log...     x 304 more times
[23:26:23.961] >  
> *
> * Visual Studio Code Server
> *
> * By using the software, you agree to
> * the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
> * the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
> *
>  
[23:26:23.980] > Server did not start successfully. Full server log at /root/.vscode-server/.1a5daa3a02319d7768e.log >>>
[23:26:23.989] > Segmentation fault (core dumped)
> <<< End of server log
> 0d7e1079a474: start
> exitCode==32==
> listeningOn====
> osReleaseId==alpine==
> arch==armv7l==
> vscodeArch==armhf==
> bitness==32==
> tmpDir==/tmp==
> platform==linux==
> unpackResult==success==
> didLocalDownload==0==
> downloadTime==0==
> installTime==0==
[23:26:23.992] > extInstallTime====
> serverStartTime==0==
> 0d7e1079a474: end
[23:26:23.993] Received install output: 
exitCode==32==
listeningOn====
osReleaseId==alpine==
arch==armv7l==
vscodeArch==armhf==
bitness==32==
tmpDir==/tmp==
platform==linux==
unpackResult==success==
didLocalDownload==0==
downloadTime==0==
installTime==0==extInstallTime====
serverStartTime==0==
[23:26:23.993] Terminating local server
[23:26:23.996] Resolver error: Error: The VS Code Server failed to start
	at g.ServerInstallError (/Users/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.0/out/extension.js:2:642224)
	at d (/Users/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.0/out/extension.js:2:635611)
	at t.handleInstallOutput (/Users/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.0/out/extension.js:2:637881)
	at e (/Users/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.0/out/extension.js:2:699953)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async /Users/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.0/out/extension.js:2:721822
	at async t.withShowDetailsEvent (/Users/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.0/out/extension.js:2:725481)
	at async /Users/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.0/out/extension.js:2:696658
	at async C (/Users/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.0/out/extension.js:2:694709)
	at async t.resolveWithLocalServer (/Users/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.0/out/extension.js:2:696198)
	at async I (/Users/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.0/out/extension.js:2:719045)
	at async t.resolve (/Users/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.0/out/extension.js:2:722852)
	at async /Users/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.0/out/extension.js:2:906656
[23:26:23.999] ------
[23:26:24.002] Local server exit: 15
```

</details>

## Steps to reproduce

After installing this addon and configuring the username and authorized_keys, I followed [the instructions provided](https://github.com/hassio-addons/addon-ssh/blob/main/ssh/DOCS.md#visual-studio-code-remote---ssh) on how to enable Visual Studio Code - Remote SSH functionality, configuring the following:
```
allow_remote_port_forwarding: true
allow_tcp_forwarding: true
```

The addon now functions normally, except when attempting to connect via Visual Studio Code.
If you need any additional information about my setup I am happy to provide!

## Proposed changes

Determine the cause, add a solution and/or update the addon documentation.

**Comment by frenck** [comment]
> The [Visual Studio Code Remote - SSH extension](https://code.visualstudio.com/docs/remote/ssh) does not work with this addon with my setup.

This add-on has been used using that extension. Just checked, and it works out of the box.

../Frenck
